-- Fix search_path for all public functions to address security warnings
DO $wrap$ BEGIN ALTER FUNCTION public.can_validate_batch(uuid, uuid) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.cleanup_expired_2fa_codes() SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.cleanup_expired_signup_otps() SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.cleanup_old_sessions() SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.count_unused_backup_codes(uuid) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.generate_batch_number() SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.get_fraud_detection_metrics(timestamp with time zone, timestamp with time zone) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.get_superior_user_id(uuid) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.get_validation_number_for_address(text, text, text, text, text) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.get_validation_stats_by_region(timestamp with time zone, timestamp with time zone) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.get_validation_stats_by_validator(timestamp with time zone, timestamp with time zone) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.get_validation_trends(timestamp with time zone, timestamp with time zone, text) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.handle_new_user() SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.has_min_level(uuid, integer) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.has_role(uuid, app_role) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.update_device_activity(uuid, text) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.update_updated_at_column() SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;
DO $wrap$ BEGIN ALTER FUNCTION public.update_validation_number_usage(text) SET search_path = public; EXCEPTION WHEN undefined_function THEN NULL; END $wrap$;