-- Setup Angola country configuration
INSERT INTO public.countries (
  country_code,
  country_name,
  is_active,
  level1_label,
  level2_label,
  level3_label,
  level4_label,
  admin_levels_count,
  requires_authority_validation,
  requires_witness_validation,
  min_witnesses_required,
  afro_id_prefix,
  phone_country_code,
  timezone,
  language_codes,
  afro_id_format
) VALUES (
  'AO',
  'Angola',
  true,
  'Província',
  'Município',
  'Comuna',
  'Bairro',
  4,
  true,
  true,
  2,
  'AO',
  '+244',
  'Africa/Luanda',
  ARRAY['pt', 'kmb', 'umb', 'ln', 'kg'],
  '{COUNTRY}-{LEVEL1}-{NUMBER}'
)
ON CONFLICT (country_code) DO UPDATE SET
  country_name = EXCLUDED.country_name,
  is_active = EXCLUDED.is_active,
  level1_label = EXCLUDED.level1_label,
  level2_label = EXCLUDED.level2_label,
  level3_label = EXCLUDED.level3_label,
  level4_label = EXCLUDED.level4_label,
  admin_levels_count = EXCLUDED.admin_levels_count,
  phone_country_code = EXCLUDED.phone_country_code,
  timezone = EXCLUDED.timezone,
  language_codes = EXCLUDED.language_codes,
  afro_id_format = EXCLUDED.afro_id_format,
  updated_at = NOW();

-- Insert 21 provinces of Angola (Level 1 divisions)
INSERT INTO public.administrative_divisions (country_code, level, code, name) VALUES
  ('AO', 1, 'AO-BGO', 'Bengo'),
  ('AO', 1, 'AO-BGU', 'Benguela'),
  ('AO', 1, 'AO-BIE', 'Bié'),
  ('AO', 1, 'AO-CAB', 'Cabinda'),
  ('AO', 1, 'AO-CCU', 'Cuando Cubango'),
  ('AO', 1, 'AO-CNO', 'Cuanza Norte'),
  ('AO', 1, 'AO-CUS', 'Cuanza Sul'),
  ('AO', 1, 'AO-CNN', 'Cunene'),
  ('AO', 1, 'AO-HUA', 'Huambo'),
  ('AO', 1, 'AO-HUI', 'Huíla'),
  ('AO', 1, 'AO-LUA', 'Luanda'),
  ('AO', 1, 'AO-LNO', 'Lunda Norte'),
  ('AO', 1, 'AO-LSU', 'Lunda Sul'),
  ('AO', 1, 'AO-MAL', 'Malanje'),
  ('AO', 1, 'AO-MOX', 'Moxico'),
  ('AO', 1, 'AO-NAM', 'Namibe'),
  ('AO', 1, 'AO-UIG', 'Uíge'),
  ('AO', 1, 'AO-ZAI', 'Zaire'),
  ('AO', 1, 'AO-ICO', 'Icolo e Bengo'),
  ('AO', 1, 'AO-LNE', 'Luanda Norte'),
  ('AO', 1, 'AO-LES', 'Luanda Este')
ON CONFLICT (country_code, level, code) DO NOTHING;