-- Add Angola to countries table
INSERT INTO public.countries (
  country_code,
  country_name,
  is_active,
  admin_levels_count,
  level1_label,
  level2_label,
  level3_label,
  level4_label,
  level5_label,
  afro_id_format,
  afro_id_prefix,
  requires_authority_validation,
  requires_witness_validation,
  min_witnesses_required,
  phone_country_code,
  phone_number_format,
  timezone,
  currency,
  language_codes,
  address_format
) VALUES (
  'AO',
  'Angola',
  true,
  4,
  'Província',
  'Município',
  'Comuna',
  'Bairro',
  'Rua',
  '{PREFIX}-{LEVEL1}-{LEVEL2}-{NUMBER}',
  'AO',
  true,
  true,
  2,
  '+244',
  '9XX XXX XXX',
  'Africa/Luanda',
  'AOA',
  ARRAY['pt'],
  '{"components": ["number", "street_name", "level4", "level3", "level2", "level1", "country"]}'::jsonb
)
ON CONFLICT (country_code) DO UPDATE SET
  country_name = EXCLUDED.country_name,
  is_active = EXCLUDED.is_active,
  admin_levels_count = EXCLUDED.admin_levels_count,
  level1_label = EXCLUDED.level1_label,
  level2_label = EXCLUDED.level2_label,
  level3_label = EXCLUDED.level3_label,
  level4_label = EXCLUDED.level4_label,
  level5_label = EXCLUDED.level5_label,
  phone_country_code = EXCLUDED.phone_country_code,
  timezone = EXCLUDED.timezone,
  currency = EXCLUDED.currency,
  language_codes = EXCLUDED.language_codes,
  updated_at = now();